import TelegramBot from 'node-telegram-bot-api';
import type { TradingSignal } from '../types';
import { getSignals, getPerformanceStats, getActiveSignals } from '../db';
import { getExplorerUrl } from '../algorand/AlgorandService';

const TOKEN = process.env.TELEGRAM_BOT_TOKEN ?? '';
const CHANNEL_ID = process.env.TELEGRAM_CHANNEL_ID ?? '';

interface BotStatus {
  connected: boolean;
  lastSignalSent?: number;
  totalMessagesSent: number;
  errors: number;
  subscribers: number;
}

let bot: TelegramBot | null = null;
let botStatus: BotStatus = {
  connected: false,
  totalMessagesSent: 0,
  errors: 0,
  subscribers: 0,
};

// Track subscribers
const subscribers = new Set<number>();

export function initTelegramBot(): void {
  if (!TOKEN || TOKEN.trim() === '') {
    console.warn('[TELEGRAM] No bot token configured - Telegram disabled');
    return;
  }

  try {
    bot = new TelegramBot(TOKEN, { polling: true });

    bot.on('polling_error', (err) => {
      console.error('[TELEGRAM] Polling error:', err.message);
      botStatus.errors++;
    });

    // Commands
    bot.onText(/\/start/, async (msg) => {
      const chatId = msg.chat.id;
      subscribers.add(chatId);
      botStatus.subscribers = subscribers.size;

      await bot!.sendMessage(chatId, `
🤖 *TradeSense AI*

Welcome to the most advanced AI-powered trading signal bot on Algorand!

Every signal is:
• Generated by real market analysis
• Verified on the Algorand blockchain
• Backed by ICT/SMC confluence

Commands:
/status — System status
/latest — Latest signal
/signals — Last 5 signals
/active — Active signals
/performance — Performance stats
/help — Help

Built for the Algorand Hackathon 🚀
      `.trim(), { parse_mode: 'Markdown' });
    });

    bot.onText(/\/help/, async (msg) => {
      await bot!.sendMessage(msg.chat.id, `
📚 *Commands*

/start — Welcome message
/status — System & market status
/latest — Latest trading signal
/signals — Last 5 signals
/active — Currently active signals
/performance — Win rate & statistics
/help — This menu
      `.trim(), { parse_mode: 'Markdown' });
    });

    bot.onText(/\/status/, async (msg) => {
      const stats = getPerformanceStats();
      await bot!.sendMessage(msg.chat.id, `
📊 *System Status*

🟢 Signal Engine: Online
🔗 Algorand App ID: ${process.env.ALGORAND_APP_ID ?? '1008'}
📱 Total Signals: ${stats.totalSignals}
✅ Active: ${stats.activeSignals}
📈 Win Rate: ${stats.winRate.toFixed(1)}%
⚡ Signals Today: ${stats.signalsToday}
      `.trim(), { parse_mode: 'Markdown' });
    });

    bot.onText(/\/latest/, async (msg) => {
      const signals = getSignals(1);
      if (!signals.length) {
        await bot!.sendMessage(msg.chat.id, '⚠️ No signals generated yet.');
        return;
      }
      await bot!.sendMessage(msg.chat.id, formatSignalMessage(signals[0]), { parse_mode: 'Markdown' });
    });

    bot.onText(/\/signals/, async (msg) => {
      const signals = getSignals(5);
      if (!signals.length) {
        await bot!.sendMessage(msg.chat.id, '⚠️ No signals generated yet.');
        return;
      }
      for (const sig of signals) {
        await bot!.sendMessage(msg.chat.id, formatSignalMessage(sig), { parse_mode: 'Markdown' });
      }
    });

    bot.onText(/\/active/, async (msg) => {
      const active = getActiveSignals();
      if (!active.length) {
        await bot!.sendMessage(msg.chat.id, '📭 No active signals currently.');
        return;
      }
      for (const sig of active) {
        await bot!.sendMessage(msg.chat.id, formatSignalMessage(sig), { parse_mode: 'Markdown' });
      }
    });

    bot.onText(/\/performance/, async (msg) => {
      const stats = getPerformanceStats();
      await bot!.sendMessage(msg.chat.id, formatPerformanceMessage(stats), { parse_mode: 'Markdown' });
    });

    // Alias: /stats → /performance
    bot.onText(/\/stats/, async (msg) => {
      const stats = getPerformanceStats();
      await bot!.sendMessage(msg.chat.id, formatPerformanceMessage(stats), { parse_mode: 'Markdown' });
    });

    // Alias: /signal → /latest
    bot.onText(/\/signal$/, async (msg) => {
      const signals = getSignals(1);
      if (!signals.length) {
        await bot!.sendMessage(msg.chat.id, '⚠️ No signals generated yet.');
        return;
      }
      await bot!.sendMessage(msg.chat.id, formatSignalMessage(signals[0]), { parse_mode: 'Markdown' });
    });

    // /verify <signalId>
    bot.onText(/\/verify\s*(.*)/, async (msg, match) => {
      const signalId = match?.[1]?.trim();
      if (!signalId) {
        const latest = getSignals(1)[0];
        if (!latest) {
          await bot!.sendMessage(msg.chat.id, '⚠️ No signals to verify.');
          return;
        }
        if (latest.algorandTxId) {
          await bot!.sendMessage(msg.chat.id, `✅ *Signal ${latest.id}*\n\n🔗 [Verify on Algorand](${getExplorerUrl(latest.algorandTxId)})\n\nApp ID: \`${latest.algorandAppId ?? 1008}\`\nTx: \`${latest.algorandTxId}\``, { parse_mode: 'Markdown' });
        } else {
          await bot!.sendMessage(msg.chat.id, `⏳ Signal ${latest.id} has not been registered on-chain yet.`);
        }
        return;
      }
      const { getSignalById } = await import('../db');
      const signal = getSignalById(signalId);
      if (!signal) {
        await bot!.sendMessage(msg.chat.id, `❌ Signal \`${signalId}\` not found.`, { parse_mode: 'Markdown' });
        return;
      }
      if (signal.algorandTxId) {
        await bot!.sendMessage(msg.chat.id, `✅ *Signal ${signal.id}*\n\n🔗 [Verify on Algorand](${getExplorerUrl(signal.algorandTxId)})\n\nApp ID: \`${signal.algorandAppId ?? 1008}\`\nTx: \`${signal.algorandTxId}\``, { parse_mode: 'Markdown' });
      } else {
        await bot!.sendMessage(msg.chat.id, `⏳ Signal \`${signal.id}\` is pending blockchain verification.`, { parse_mode: 'Markdown' });
      }
    });

    // /markets
    bot.onText(/\/markets/, async (msg) => {
      try {
        const { getAllPrices } = await import('../market/MarketDataProvider');
        const prices = await getAllPrices();
        const lines = prices.map(p => {
          const dir = p.changePct24h >= 0 ? '▲' : '▼';
          return `*${p.symbol}*: $${p.price.toLocaleString('en-US', {maximumFractionDigits: 2})} ${dir} ${Math.abs(p.changePct24h).toFixed(2)}%`;
        });
        await bot!.sendMessage(msg.chat.id, `📊 *Markets*\n\n${lines.join('\n')}`, { parse_mode: 'Markdown' });
      } catch {
        await bot!.sendMessage(msg.chat.id, '⚠️ Market data temporarily unavailable.');
      }
    });

    botStatus.connected = true;
    console.log('[TELEGRAM] ✅ Bot initialized successfully');
  } catch (err) {
    console.error('[TELEGRAM] Failed to initialize bot:', err);
    botStatus.errors++;
  }
}

// ─── Message Formatters ───────────────────────────────────────────────────────
function formatSignalMessage(signal: TradingSignal): string {
  const emoji = signal.direction === 'LONG' ? '🟢' : '🔴';
  const dirLabel = signal.direction === 'LONG' ? 'LONG' : 'SHORT';
  
  const aiReasoning = signal.geminiReasoning 
    ? signal.geminiReasoning.map(r => `• ${r}`).join('\n')
    : '• No AI reasoning provided';
    
  const risks = signal.riskFactorsArr 
    ? signal.riskFactorsArr.map(r => `• ${r}`).join('\n')
    : '• Standard market risks apply';

  const trend = signal.technicalFactors?.trend || 'Neutral';
  const structure = signal.structureFactors?.length ? signal.structureFactors[signal.structureFactors.length - 1].direction : 'Consolidation';
  const volume = signal.volumeAnalysis?.volumeState || 'Average';
  const liquidity = signal.liquidityAnalysis?.nearestPool ? `Nearest Pool: ${signal.liquidityAnalysis.nearestPool}` : 'Neutral';
  const momentum = signal.technicalFactors?.rsi > 60 ? 'Strong Bullish' : signal.technicalFactors?.rsi < 40 ? 'Strong Bearish' : 'Neutral';

  const blockchainLine = signal.algorandTxId
    ? `⛓️ Algorand Verified\nApp ID: ${signal.algorandAppId ?? 1008}\nTx: ${signal.algorandTxId}`
    : '⏳ Blockchain verification pending';

  let newsSection = '';
  if (signal.newsData) {
    const newsEffect = signal.newsData.signalEffect.includes('SUPPORTS') ? '🟢' : signal.newsData.signalEffect.includes('CONTRADICTS') ? '⚠️' : '⚪';
    newsSection = `
📰 *NEWS INTELLIGENCE*

*Bias Score:* ${signal.newsData.biasScore > 0 ? '+' : ''}${signal.newsData.biasScore} (${signal.newsData.biasStatus.replace('_', ' ')})
*Impact:* ${signal.newsData.impact}
*Effect:* ${newsEffect} ${signal.newsData.signalEffect.replace('_', ' ')}
*Reason:* ${signal.newsExplanation || 'N/A'}
`;
  }

  return `
🚨 *AI TRADING SIGNAL*

*${signal.symbol.replace('/', '')}*

${emoji} *${dirLabel}*

*Entry:* \`${formatPrice(signal.entry, signal.symbol)}\`
*Stop Loss:* \`${formatPrice(signal.stopLoss, signal.symbol)}\`
*Take Profit:* \`${formatPrice(signal.takeProfit, signal.symbol)}\`

*Risk/Reward:* \`1:${signal.riskReward.toFixed(2)}\`
*Confidence:* ${signal.confidence.toFixed(0)}%

*QUANT SCORE:* ${signal.quantScore?.toFixed(0) || 'N/A'}
*TRADE SENSE AI SCORE:* ${signal.geminiScore?.toFixed(0) || 'N/A'}

📊 *MARKET ANALYSIS*

*Trend:* ${trend}
*Structure:* ${structure}
*Volume:* ${volume}
*Liquidity:* ${liquidity}
*Momentum:* ${momentum}

🤖 *AI REASONING*

${aiReasoning}
${newsSection}
⚠️ *RISKS*

${risks}

${blockchainLine}
  `.trim();
}

function formatPerformanceMessage(stats: ReturnType<typeof getPerformanceStats>): string {
  return `
📊 *Performance Statistics*

Total Signals: ${stats.totalSignals}
✅ Wins: ${stats.wins}
❌ Losses: ${stats.losses}
📈 Win Rate: *${stats.winRate.toFixed(1)}%*

Avg Risk/Reward: ${stats.avgRR.toFixed(2)}
Profit Factor: ${stats.profitFactor.toFixed(2)}
Avg Confidence: ${stats.avgConfidence.toFixed(1)}%

📅 Signals Today: ${stats.signalsToday}
⚡ Active Now: ${stats.activeSignals}
🏆 Best Strategy: ${stats.bestStrategy}
  `.trim();
}

function formatPrice(price: number, symbol: string): string {
  if (symbol.includes('BTC')) return price.toLocaleString('en-US', { minimumFractionDigits: 0, maximumFractionDigits: 0 });
  if (symbol.includes('ETH')) return price.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
  return price.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
}

// ─── Broadcast ────────────────────────────────────────────────────────────────
export async function broadcastSignal(signal: TradingSignal): Promise<void> {
  if (!bot) {
    console.warn('[TELEGRAM] Bot not initialized - skipping broadcast');
    return;
  }

  const message = formatSignalMessage(signal);
  const chatIds = new Set<string | number>();

  // Add channel if configured
  if (CHANNEL_ID) chatIds.add(CHANNEL_ID);

  // Add individual subscribers
  subscribers.forEach(id => chatIds.add(id));

  for (const chatId of chatIds) {
    try {
      await bot.sendMessage(chatId, message, { parse_mode: 'Markdown' });
      botStatus.totalMessagesSent++;
      botStatus.lastSignalSent = Date.now();
    } catch (err) {
      console.error(`[TELEGRAM] Failed to send to ${chatId}:`, err);
      botStatus.errors++;
    }
  }

  console.log(`[TELEGRAM] Signal broadcast to ${chatIds.size} chat(s)`);
}

export async function sendMessageToAll(message: string): Promise<void> {
  if (!bot) return;

  const chatIds = new Set<string | number>();
  if (CHANNEL_ID) chatIds.add(CHANNEL_ID);
  subscribers.forEach(id => chatIds.add(id));

  for (const chatId of chatIds) {
    try {
      await bot.sendMessage(chatId, message, { parse_mode: 'Markdown' });
      botStatus.totalMessagesSent++;
    } catch (err) {
      console.error(`[TELEGRAM] Error sending to ${chatId}:`, err);
      botStatus.errors++;
    }
  }
}

export function getBotStatus(): BotStatus {
  return { ...botStatus, subscribers: subscribers.size };
}

export function isConnected(): boolean {
  return botStatus.connected;
}
